### ISSUE TITLE
Increase number of bots

### ISSUE THREAD

**Issue by sidwise** [Pure-L0G1C/Instagram#100]
I want to edit the code so I can increase the number of bots could you tell me how to do it please, thanks

**Comment by Pure-L0G1C** [comment]
Join my discord https://discord.gg/ZGSwXZ

**Comment by sidwise** [comment]
Invalid discord

**Comment by Pure-L0G1C** [comment]
It was a temporary link. Try https://discord.gg/jvhJMeb

**Comment by Pure-L0G1C** [comment]
I have increased bots number in version 3.0.0 https://youtube.com/watch?v=l6B9BaslDS8
