### ISSUE TITLE
Insta brtefrce get stuck or stop when attempt, complete status or browser becomes, any two of them get  equal in number. thanks

### ISSUE THREAD

**Issue by lShazl** [Pure-L0G1C/Instagram#151]
Hi Pure, hope you are doing good, i had followed your setps for insta brtefrce but found an issue. 
when the the complete status while scanning the password the percentage and attempts or browsers counts becomes the same any of two from these 3 becomes the same the scan gets held or stop. 
i am attaching the file for reference. u can see the count where the complete status say 0.095% and attempts at 95 as well. kindly check this issue. it comes when any of the three options becomes equal, browser/attempts/complete status in same numbers. screenshot is attached. i always have to restart the scan once the values become equal which then again start from the beginning. thanks looking to hear from you soon Pure. 

![brteforceinsta](https://user-images.githubusercontent.com/7135390/81424212-089b1500-916f-11ea-9837-6b9deff5ad68.PNG)

**Comment by Pure-L0G1C** [comment]
https://discord.gg/HDyARWh
