### ISSUE TITLE
tor instaling

### ISSUE THREAD

**Issue by idkwhoiiam** [Pure-L0G1C/Instagram#19]
how to install tor

**Comment by Juniorn1003** [comment]
sudo apt-get install tor

**Comment by knavihs** [comment]
it says tor has no installation candidate
$sudo apt-get install tor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package tor is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'tor' has no installation candidate
???

**Comment by Ethical-H4CK3R** [comment]
```sh
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && apt-get update && apt-get install tor -y && apt autoremove -y
```

**Comment by NicolasJax** [comment]
It's working. Thanks..

**Comment by kabbu59** [comment]
root@kali:~# echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list && apt-get update && apt-get install tor -y && apt autoremove -y
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/

please help it's very urgent ....

**Comment by Ethical-H4CK3R** [comment]
Run: ‘pkill apt-get’ Then try again
