### ISSUE TITLE
False correct passwords

### ISSUE THREAD

**Issue by jbtzx123** [Pure-L0G1C/Instagram#22]
Keeps giving a password and saying it’s correct but turns out to be wrong when actually tested.

**Comment by Ethical-H4CK3R** [comment]
I got a bit lazy towards the end of creating this program that why it have annoying bugs, but my new program hyprPulse I actually kinda tried; I got lazy, but as lazy as writing this program. In this program I only had one way to test the validity of the password, but in the new program I have two ways to check it. I’ll add a third way once it starts giving the wrong passwords.

**Comment by jbtzx123** [comment]
Where is the new program?

**Comment by Ethical-H4CK3R** [comment]
It’s on my page

**Comment by Ethical-H4CK3R** [comment]
It’s called hyprPulse: https://github.com/Ethical-H4CK3R

**Comment by Ethical-H4CK3R** [comment]
HyprPulse: https://github.com/Ethical-H4CK3R/hyprPulse

**Comment by jbtzx123** [comment]
I tried it and it started at first, but now i keep getting disconnected from my ethernet connection whenever i try to use it again. Any advice?

**Comment by jbtzx123** [comment]
Seems to be stuck on obtaining proxy IP when disconnection from internet

**Comment by jbtzx123** [comment]
Why did tor stop working suddenly and how can i fix it?

**Comment by mojipkfr77** [comment]
use this program , you can crack instagram accounts without proxy & tor : https://github.com/mojipkfr77/InstaBruteForce/

**Comment by Ethical-H4CK3R** [comment]
Hacking without a proxy is not smart at all. That’s how most of noobs end up in jail, because they refuse  to use a proxy.

**Comment by mojipkfr77** [comment]
hahahahaha... what the fuck ??? jail?? so funny 😂
