### ISSUE TITLE
password

### ISSUE THREAD

**Issue by hamad12125** [Pure-L0G1C/Instagram#25]
why when it finish like the first 5 lines of passwords it doesn't change it loops the password like 
start:
me
me2
m3
it goes back to 
me
me2
m3

**Comment by Ethical-H4CK3R** [comment]
The program is encountering a 404 error because Instagram change their login page. I’ll fix it when I get around to it. At the time use my other program called hyprPulse; Instagram doesn’t work, but you can still use it on Facebook and Twitter.

**Comment by hamad12125** [comment]
ok thanks keep it up 👍

**Comment by hamad12125** [comment]
if you need anything just tell me :) <3
discord : hamad12125#2942

**Comment by Ethical-H4CK3R** [comment]
@hamad12125 I need a donation, is that something you can help with?

**Comment by susyaj** [comment]
Hi 

Where i cant the download link...
Pleas answer me

**Comment by Ethical-H4CK3R** [comment]
in your Kali Linux terminal try typing: git clone
https://github.com/Ethical-H4CK3R/Instagram
