### ISSUE TITLE
Always Searching for proxies ...

### ISSUE THREAD

**Issue by louis98989** [Pure-L0G1C/Instagram#30]
After run python instagram.py
Always Searching for proxies ...
What should I do to fix the issue?
Thanks.

**Comment by Pure-L0G1C** [comment]
Make sure your internet is working

**Comment by louis98989** [comment]
Internet is fine.
Or I need to disable the firewall?

**Comment by Pure-L0G1C** [comment]
No you shouldn’t have to. It might be that the framework can’t find the
right type of proxies.

**Comment by louis98989** [comment]
Thanks for reply
It works after reinstall the Ubuntu
