### ISSUE TITLE
unable to locate pass.lst

### ISSUE THREAD

**Issue by acilard69** [Pure-L0G1C/Instagram#31]
python instagram.py Sami09.1 pass.lst 16                                          
please respon

**Comment by Pure-L0G1C** [comment]
Take a look at [this](https://github.com/Pure-L0G1C/InstaBurst/issues/14)

**Comment by Prabha10cs** [comment]
@Pure-L0G1C 
python instagram.py Sami09.1 pass.lst 16
[!] Unable to locate `pass.lst`
how to solve this
