### ISSUE TITLE
Suspicious Login Attempt

### ISSUE THREAD

**Issue by MehmetAliCan10** [Pure-L0G1C/Instagram#32]
Hi

Can you maybe fix it Suspicious Login Attempt.
without showing this?

**Comment by Pure-L0G1C** [comment]
Wait do you mean by suspicious login attempt? Are the attempts not going through?

**Comment by MehmetAliCan10** [comment]
I have me self password found but , instagram app seen, " We detected An unusual Login attempt."

**Comment by Pure-L0G1C** [comment]
I don’t know how to bypass that yet. But once I figure a bypass, I’ll implement it into the program.

**Comment by MehmetAliCan10** [comment]
Ok thanks,

**Comment by MehmetAliCan10** [comment]
How can I proxy-ip to want or 1 country set?

**Comment by Pure-L0G1C** [comment]
you can but that will cause the whole process to go slow.

**Comment by Pure-L0G1C** [comment]
You would have to modify the http url of proxy_url in the path
Instagram/lib/src/lib/const.py

After you can add to the proxy_url any country code you want.
Example:
   &country=USA

**Comment by MehmetAliCan10** [comment]
File "/root/Desktop/Instagram-master/lib/src/lib/const.py", line 5
    &country=USA
    ^
SyntaxError: invalid syntax

get error I do no understand example "&country=USA "....

**Comment by MehmetAliCan10** [comment]
I need turkey and Belguim proxy url  I do no know how change code...

**Comment by Pure-L0G1C** [comment]
I couldn’t find any usable proxies from either of those countries

**Comment by MehmetAliCan10** [comment]
https://www.proxydocker.com/en/proxylist/country/Belgium

I have found proxy so how do I code PROXY_URL  and HEADER_DETAILS?
