### ISSUE TITLE
[-] Attempts: 0 Long time no Attempts

### ISSUE THREAD

**Issue by 0x337** [Pure-L0G1C/Instagram#35]
SALAM ALYKOM Brother ^^ 
The Script keeps trying but without any attempts, attempts won't change
---
[-] Proxy-IP: 128.68.220.85[FR]
[-] Wordlist: pass.txt
[-] Username: InstaUser
[-] Password: hsa11445
[-] Attempts: 0
[-] Proxies: 39
---
any solution or suggestion akhi ^^

**Comment by hamadberlin** [comment]
same here

**Comment by HuhMe9** [comment]
good thank you.

**Comment by hamadberlin** [comment]
still no solution? :(

**Comment by HuhMe9** [comment]
[-] Proxy-IP:
[-] Wordlist: realuniq.lst
[-] Username: N4R.1
[-] Password:
[-] Attempts: 0
[-] Proxies: 0

[+] Searching for proxies ...



i waiting 2h ;)

**Comment by 0x337** [comment]
Never mind brO ♥ take your time , My suggestion is to make the script offer u to choose between setting proxy manual or automatic it will be so helpful , and i would thank u for your efforts never give up u are the best ;) SALAM

**Comment by HuhMe9** [comment]
add new option : -p = proxy file
