### ISSUE TITLE
Proxy Searching Forever 

### ISSUE THREAD

**Issue by Ali-Rezaie** [Pure-L0G1C/Instagram#40]
when I use My own username and password list ( just for checking if it works ) it starts to connect to a proxy but its search never finishes :

searching for Proxies .... 

and no result :(

**Comment by Ali-Rezaie** [comment]
@Pure-L0G1C then what should I do to fix this?

**Comment by telewolf653** [comment]
@Ali-Rezaie use external proxies to work...

**Comment by telewolf653** [comment]
With other sources(that you can choose proxies file)
