### ISSUE TITLE
not quite sure what i'm doing

### ISSUE THREAD

**Issue by whispertrees** [Pure-L0G1C/Instagram#41]
When I downloaded the file,  (I have Python and Tor) the python app opened and then quickly closed. i dont know where to input any of this, i'm pretty new to this

**Comment by Pure-L0G1C** [comment]
The instructions are on the READMe file

**Comment by whispertrees** [comment]
yes, i get that, but i dont know where to input them

**Comment by Pure-L0G1C** [comment]
Command line cmd

**Comment by whispertrees** [comment]
sorry for wasting your time and all, but i put the 'help' phrase 'C:\Users\Mohamed\Desktop\Instagram>python instagram.py Sami09.1 pass.lst 16' (without the C:\Users\Mohamed) into the command line and it keeps saying it cant find the path specificed

also thank you for taking the time to reply

**Comment by Pure-L0G1C** [comment]
You have to open the folder of where the program is located and then in the
search bar of that folder type cmd and then command line should open

**Comment by whispertrees** [comment]
Managed to set it up and got it to work, but now it keeps saying "no module named requests" from "Requests import section" and everytime i attempt to input the command in the readme, it sends the same message

**Comment by Pure-L0G1C** [comment]
pip install requests

**Comment by whispertrees** [comment]
Did that! Can't locate pass.lst, however, is an error that I am getting

**Comment by Pure-L0G1C** [comment]
Make sure you generate the pass.lat using the password generator program

**Comment by whispertrees** [comment]
Ah! Thank you so much! It works now. You're the best! If there are issues I will update
