### ISSUE TITLE
Suggestion for proxy problem

### ISSUE THREAD

**Issue by HuhMe9** [Pure-L0G1C/Instagram#43]
add new option : -p = proxy file    👍

**Comment by Pure-L0G1C** [comment]
It will be pointless after a while. Not every proxy in the file will be
accepted be Instagram. After maybe 30 minutes, all the proxies will go bad.
The program changes to a new proxy after 16 attempts, and imagine if you
1000 passwords, you would need about 63 different proxies. Else Instagram
will respond with a 429 or a 403 response.

**Comment by HuhMe9** [comment]
Okay what about proxybroker it's good

See this page: https://pypi.org/project/proxybroker/
