### ISSUE TITLE
[!] Unable to locate [username]

### ISSUE THREAD

**Issue by xAnghellic** [Pure-L0G1C/Instagram#44]
Has anyone ever had a problem with it saying [!] Unable to locate [username here] but the username is an actual one on instagram? Trying to help a friend recover her account

**Comment by Pure-L0G1C** [comment]
Yeah, it says that when the account isn’t verified. I’m going have to
disable that feature.

**Comment by Pure-L0G1C** [comment]
Haha, sorry that was a feature in an older version of this program, to fix you just put in the data the wrong way. python instagram.py [her_username] [passwords_file] [threads]. Example: python instagram.py Sami09.1 word.lst 16

**Comment by xAnghellic** [comment]
That gave me: usage: instagram.py [-h] username wordlist threads
instagram.py: error: too few arguments
and if i add [-h] to it, it says unable to find [username] again. Am I doing something wrong to where I get the "too few arguments" error? I have it pointed to the password list correctly and all that.

Thanks!

**Comment by Pure-L0G1C** [comment]
Make sure you separate the sections by spaces. The program is looking for
sections, the first section is the username the second section is the
password file and the third section is the threads

**Comment by xAnghellic** [comment]
Got it working! Thank you sir for the speedy responses! How many attempts on average does it use per proxy? Is there a way to add more proxies to the list? Sorry, I'm new to all of this. Thanks again!

**Comment by Pure-L0G1C** [comment]
Instagram only accepts 16 passwords per proxy before waiting. The program
will automatically find new proxies every time it runs out.

**Comment by xAnghellic** [comment]
So currently for me it says "392 remaining". When it hits 0, it automatically gets some more? Appreciate the help man. Feel free to close this after.

**Comment by Pure-L0G1C** [comment]
Yeah, it will get some more once it hits 0. And just in case something
happens and you have to restart the program again, it will pick up where it
left off.
