### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by sadeg1377** [Pure-L0G1C/Instagram#54]
Hi
searching for proxy does not work for me and my attempt is 0 and also I use proxychains but it is not  working

**Comment by jasmineramona** [comment]
Contact me if you need instagram hacking services 

Email:       jasmineramona@protonmail.com

**Comment by mateocam** [comment]
Hello !

I am having the same issue. I left the program running for 30 minutes and this is the only output I got:

[-] Proxy-IP: 
[-] Wordlist: rockyou.txt
[-] Username: <<username>>
[-] Password: 
[-] Attempts: 0
[-] Proxies: 0

[+] Searching for proxies ...

why is this happening ?

**Comment by sshkrv** [comment]
> Hello !
> 
> I am having the same issue. I left the program running for 30 minutes and this is the only output I got:
> 
> [-] Proxy-IP:
> [-] Wordlist: rockyou.txt
> [-] Username: <>
> [-] Password:
> [-] Attempts: 0
> [-] Proxies: 0
> 
> [+] Searching for proxies ...
> 
> why is this happening ?

same for me

**Comment by wolfwar22** [comment]
Hi sir

How are 

Please learn me how to add proxy list txt on termux?


How to use and add proxy to termux
I waiting for answer 
Freefollowersserver@gmail.com

**Comment by Pure-L0G1C** [comment]
@wolfwar22 The program automatically finds the proxies it needs to run, no need to have a proxy list

**Comment by Pure-L0G1C** [comment]
@wolfwar22 I don’t use Thermox, I actually don’t know anything about it, but I found the following video on YouTube. https://youtube.com/watch?v=9h86HZAB1Jw

**Comment by wolfwar22** [comment]
I saw this movie ... it does not really tell you the details just
write it just clears it in the movie ..

The command code in the movie is not properly explained sir


در تاریخ یکشنبه ۹ دسامبر ۲۰۱۸،‏ ۱۹:۰۷ Mohamed <notifications@github.com>
نوشت:

**Comment by Pure-L0G1C** [comment]
@wolfwar22 I don’t know how to help you

**Comment by wolfwar22** [comment]
Is very very esay... I just want to know what code you use in thermux

در تاریخ یکشنبه ۹ دسامبر ۲۰۱۸،‏ ۱۹:۵۰ Mohamed <notifications@github.com>
نوشت:

**Comment by Pure-L0G1C** [comment]
@wolfwar22 I don’t, but I found another video you ca try https://youtube.com/watch?v=dl8cqvb6xTc

**Comment by wolfwar22** [comment]
Thank you so much for the
sir😙😙😙😙😙😙💋💋💋😙💋😙😙💋😙😙😙💚💚😊💚💚😊😊😊😊😊😊😊 ....
forgive me bothering you


در تاریخ یکشنبه ۹ دسامبر ۲۰۱۸،‏ ۲۰:۱۰ Mohamed <notifications@github.com>
نوشت:

**Comment by Pure-L0G1C** [comment]
@wolfwar22 Thanks would’ve been enough
