### ISSUE TITLE
Improve service required

### ISSUE THREAD

**Issue by aziz42424** [Pure-L0G1C/Instagram#55]
Hi dear,

I have 2 recommends to improve the tool which work perfectly with me.

1. Allow user to select exit node of proxy. When get success, it will notify the victim about suspecious activity from different country. I assume this will help fix the problem.

2. Add ability to search by phone# or email address for accounts.

Thanks

**Comment by Pure-L0G1C** [comment]
These don’t sound like any useful features.

The program doesn’t know what password is going to be the correct password,
so it won’t be able to know when to change to a proxy from the same
country. And the program can’t be reusing the same proxy it has to switch
between many of them.

How would the searching feature work? How would it a real use?

**Comment by Pure-L0G1C** [comment]
it would be pointless to do one more try using the selected proxy because
the owner would be alerted  the first time the program gains access.

By the way you shouldn’t be using this program maliciously. Brute force
your own account or ask for permission from the person before you do.
