### ISSUE TITLE
Program freeze

### ISSUE THREAD

**Issue by sirserpico** [Pure-L0G1C/Instagram#57]
Hi, I dont' know why the program stops at the 1004 attempt, I've tried many wordlists and accounts but it stops always at 1004, how i can resolve?

**Comment by netcxt001** [comment]
Code your own tools you fucking script kiddie

**Comment by Pure-L0G1C** [comment]
@netcxt001 chill out man

**Comment by Pure-L0G1C** [comment]
Check out my latest version, most of the issues with this version have been resolved. https://youtube.com/watch?v=l6B9BaslDS8

**Comment by netcxt001** [comment]
Boi you did it. But the old version of instagram had more vulnerability,
that was easy af finding 0days. Did you got any 0days?

**Comment by theamazingwaffle** [comment]
@Pure-L0G1C That video is unavailable :(
