### ISSUE TITLE
problem in code

### ISSUE THREAD

**Issue by mortalwolf** [Pure-L0G1C/Instagram#58]
Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter 
  File "/home/mortalwolf/Desktop/Code/Instagram/lib/bruter.py", line 5, in <module>
    from .spyder import Spyder 
  File "/home/mortalwolf/Desktop/Code/Instagram/lib/spyder.py", line 7, in <module>
    from .scraper import Scraper, Queue 
  File "/home/mortalwolf/Desktop/Code/Instagram/lib/scraper.py", line 6, in <module>
    from bs4 import BeautifulSoup as bs 
ImportError: No module named bs4

**Comment by sengbh** [comment]
I have the same issue.  It is below:

Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter 
  File "/root/Instagram/lib/bruter.py", line 5, in <module>
    from .spyder import Spyder 
  File "/root/Instagram/lib/spyder.py", line 7, in <module>
    from .scraper import Scraper, Queue 
  File "/root/Instagram/lib/scraper.py", line 6, in <module>
    from bs4 import BeautifulSoup as bs 
ModuleNotFoundError: No module named 'bs4'

**Comment by Leuchtmarker** [comment]
try to run `pip install beautifulsoup4`

**Comment by sengbh** [comment]
It worked with mine beautifully.  Do these two options:

1. redo everything from scratch
2. update to the latest python.

**Comment by MrNobodyTharusha** [comment]
Hey it's working....  thank you...

**Comment by rippledude123** [comment]
Traceback (most recent call last):
  File "instagram.py", line 8, in <module>
    from lib.bruter import Bruter
  File "/root/Instagram/lib/bruter.py", line 5, in <module>
    from .spyder import Spyder
  File "/root/Instagram/lib/spyder.py", line 5, in <module>
    from requests import Session
ImportError: No module named requests

I get this error what do I do to fix? Thnx in advance 👍

**Comment by joanamelo13** [comment]
Traceback (most recent call last): File "instagram.py", line 6, in <module> from lib.bruter import Bruter ImportError: No module named lib.bruter what is a problem? HELP ME﻿

**Comment by sengbh** [comment]
@rippledude123 

You need to install the module named requests

- sudo pip3 install requests (Python3 with pip3 installed)
-sudo pip install requests (general with pip installed)

or 
 -sudo apt-get install python-requests

**Comment by Pure-L0G1C** [comment]
Join the [Discord server](https://discord.gg/SMUaWmn)

**Comment by karthikey06** [comment]
from lib.bruter import Bruter
ModuleNotFoundError: No module named 'lib.bruter'
, i dont know ..how could i solve this..please help me

**Comment by Pure-L0G1C** [comment]
If you’re on Windows go into the the folders named Executable/executable there should be an executable named Instagram.exe

**Comment by Ramin333** [comment]
What i should do ??????? 
Traceback (most recent call last):
  File "instagram.py", line 6, in <module>
    from lib.bruter import Bruter
  File "/home/R3/Instagram/lib/bruter.py", line 8, in <module>
    from .display import Display
  File "/home/R3/Instagram/lib/display.py", line 8, in <module>
    from colorama import Fore
ImportError: No module named colorama

**Comment by Pure-L0G1C** [comment]
You should run the install.py file

**Comment by Ramin333** [comment]
when i try to run "install.py"
that's what happend
--------------
Traceback (most recent call last):
  File "install.py", line 6, in <module>
    from queue import Queue
ImportError: No module named queue

**Comment by Pure-L0G1C** [comment]
What version of Python are you running?

**Comment by Ramin333** [comment]
Python 2.7.15rc1

**Comment by Pure-L0G1C** [comment]
Try updating it

**Comment by Ramin333** [comment]
it's Python 3.6.7 Now

**Comment by Pure-L0G1C** [comment]
Did it work?

**Comment by Ramin333** [comment]
No

[+] Installing bs4 ...
[!] Failed to install bs4


[+] Installing future ...
[!] Failed to install future


[+] Installing requests ...
[!] Failed to install requests


[+] Installing colorama ...
[!] Failed to install colorama

**Comment by Pure-L0G1C** [comment]
Make sure your internet is working

**Comment by Ramin333** [comment]
my internet is Ok
.

**Comment by Ramin333** [comment]
my internet is working well.

**Comment by Pure-L0G1C** [comment]
Run the following code: pip install -r requirements.txt

**Comment by MrNobodyTharusha** [comment]
Didn't you try it with pip2 ?

pip2 install -r requirements.txt
pip2 install requests

**Comment by Ramin333** [comment]
no
i just read
README.md
Thank you very much for helping me ( :

**Comment by MrNobodyTharusha** [comment]
It's ok broo...  U  r wellcome  :-)

**Comment by dhoni9500** [comment]
Please help wt to do now
Traceback (most recent call last):
  File "instagram.py", line 7, in <module>
    from lib.bruter import Bruter
  File "/data/data/com.termux/files/home/Instagram/lib/bruter.py", line 7, in <module>
    from lib.display import Display
  File "/data/data/com.termux/files/home/Instagram/lib/display.py", line 8, in <module>
    from colorama import Fore
ModuleNotFoundError: No module named 'colorama'

**Comment by wallbloggerboy** [comment]
do pip install -r requirements.txt

**Comment by mynk1412** [comment]
> do pip install -r requirements.txt

Hey after this command it is showing this 👇
usage: instagram.py [-h] [-nc] [-m MODE] username passlist
instagram.py: error: the following arguments are required: username, passlist

**Comment by SNethajiR** [comment]
1. pip3 install -r requirements.txt

 2. python3 instagram.py (username) (wordlist.txt)

it works for me....

**Comment by swlh3099** [comment]
> 1. pip3 install -r requirements.txt
> 2. python3 instagram.py (username) (wordlist.txt)
> 
> it works for me....

**Comment by swlh3099** [comment]
> Traceback (most recent call last):
> File "instagram.py", line 8, in
> from lib.bruter import Bruter
> File "/home/swlh3099/Desktop/Code/Instagram/lib/swlh309.py", line 5, in
> from .spyder import Spyder
> File "/home/mortalwolf/Desktop/Code/Instagram/lib/swlh309.py", line 7, in
> from .scraper import Scraper, Queue
> File "/home/mortalwolf/Desktop/Code/Instagram/lib/scraper.py", line 6, in
> from bs4 import BeautifulSoup as bs
> ImportError: No module named bs4
