### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by houseddrk** [Pure-L0G1C/Instagram#67]
Dear ,
how to setup proxy for this program?

is there a chance if i used it alot that may instagram block my ip to login API?

**Comment by Pure-L0G1C** [comment]
No, the program doesn’t need your help to cover its tracks, just don’t uses it for illegal purposes

**Comment by abbasgol** [comment]
Thank you ,
so i the password list over 5000 password, the program will go through all the list right?

**Comment by Pure-L0G1C** [comment]
I programmed it to try everything, and to retry it if it gets a weird response, just don’t abuse it

**Comment by nuriodaci** [comment]
it stuck searching for proxies ...

**Comment by Pure-L0G1C** [comment]
@nuriodaci thanks for letting me know, I’ll look into it as soon as possible. 

What OS are you using? What version of Python are you running? How much RAM does your pc have? 

How is your internet speed like? Do you use VPN to bypass geofencing? What country do you live in?

**Comment by nuriodaci** [comment]
@Pure-L0G1C 
Windows 10
Python 2.7
4GB Ram
7-8 Mpbs internet
I don't use VPN
Turkey 
:)

**Comment by Pure-L0G1C** [comment]
@nuriodaci can you access the following links? `https://sslproxies.org`, `https://free-proxy-list.net`,        
 `https://free-proxy-list.net/anonymous-proxy.html`, `http://spys.me/proxy.txt`
