### ISSUE TITLE
unable to find proxy server 

### ISSUE THREAD

**Issue by smrst** [Pure-L0G1C/Instagram#72]
hey , 
when i run the commend, after checking some password character , i get this error :
[!] Failed to grab proxies from http://spys.me/proxy.txt 
tried to find the code on instagram.py and setup.py to edit or add proxy . didnt find anything . 
does anyone know why is that ?

**Comment by Pure-L0G1C** [comment]
Just ignore it. It has a few other sites it searches the proxies from.

**Comment by Pure-L0G1C** [comment]
What service provider did you change. If don't know what you're doing don't mess with it because you might get your IP block-listed. 

The code runs through every password in the list you provide and will test each one and give you the correct one. Just don't mess with anything if you don't what you're doing

**Comment by smrst** [comment]
from a private company to a governmental one . i dont know whether it makes sense or not .  does it ?

**Comment by Pure-L0G1C** [comment]
No, it doesn’t. What section of code did you change.

**Comment by smrst** [comment]
from a private company to a governmental one . i dont know whether it makes sense or not .  does it ? 
the first one was like stuck. everything was freeze but the second one it worked really well . 
- also trying to find the combination of 13 letters and numbers online , found the code . just adding the passwords to the list file , not the code to Instagram file . 
it also says its too large . is there any language supporting this length ?

**Comment by smrst** [comment]
my bad , "internet service provider ", sure , here is the code : and the error : 
# Python 3 program to print all 
# possible strings of length k 
	
# The method that prints all 
# possible strings of length k. 
# It is mainly a wrapper over 
# recursive function printAllKLengthRec() 
def printAllKLength(set, k): 

	n = len(set) 
	printAllKLengthRec(set, "", n, k) 

# The main recursive method 
# to print all possible 
# strings of length k 
def printAllKLengthRec(set, prefix, n, k): 
	
	# Base case: k is 0, 
	# print prefix 
	if (k == 0) : 
		print(prefix) 
		return

	# One by one add all characters 
	# from set and recursively 
	# call for k equals to k-1 
	for i in range(n): 

		# Next character of input added 
		newPrefix = prefix + set[i] 
		
		# k is decreased, because 
		# we have added a new character 
		printAllKLengthRec(set, newPrefix, n, k - 1) 

# Driver Code 
if __name__ == "__main__": 
	
	print("First Test") 
	set1 = ['1', '2', '3', '4', '5', '.', '6', '0', '7', '8', '9', 'a', 'b'] 
	k = 13
	printAllKLength(set1, k) 
	

# This code is contributed 
# by ChitraNayal

**Comment by smrst** [comment]
my bad . "internet service provider " . sure here is the code i got online to print all possible combination of the guessed password  : 
# Python 3 program to print all 
# possible strings of length k 
	
# The method that prints all 
# possible strings of length k. 
# It is mainly a wrapper over 
# recursive function printAllKLengthRec() 
def printAllKLength(set, k): 

	n = len(set) 
	printAllKLengthRec(set, "", n, k) 

# The main recursive method 
# to print all possible 
# strings of length k 
def printAllKLengthRec(set, prefix, n, k): 
	
	# Base case: k is 0, 
	# print prefix 
	if (k == 0) : 
		print(prefix) 
		return

	# One by one add all characters 
	# from set and recursively 
	# call for k equals to k-1 
	for i in range(n): 

		# Next character of input added 
		newPrefix = prefix + set[i] 
		
		# k is decreased, because 
		# we have added a new character 
		printAllKLengthRec(set, newPrefix, n, k - 1) 

# Driver Code 
if __name__ == "__main__": 
	
	print("First Test") 
	set1 = ['1', '2', '3', '4', '5', '.', '6', '0', '7', '8', '9', 'a', 'b'] 
	k = 13
	printAllKLength(set1, k) 
	

# This code is contributed 
# by ChitraNayal

**Comment by smrst** [comment]
and here is the output error : 

Traceback (most recent call last):
  File "/home/01c55f881125566deaed43a5703cf580.py", line 42, in <module>
    printAllKLength(set1, k) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 11, in printAllKLength
    printAllKLengthRec(set, "", n, k) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 34, in printAllKLengthRec
    printAllKLengthRec(set, newPrefix, n, k - 1) 
  File "/home/01c55f881125566deaed43a5703cf580.py", line 21, in printAllKLengthRec
    print(prefix) 
OSError: [Errno 27] File too large

**Comment by Pure-L0G1C** [comment]
That’s no my code, so, I can’t help you with it. Also, generating every possible combination will take you years to guess the correct password. You need a password list

**Comment by smrst** [comment]
correct . so i delete that post . i was trying to make the password list by that online code . it works on 3 combination but not more . to make this kind of password list ?
