### ISSUE TITLE
Browsers stop renewing

### ISSUE THREAD

**Issue by NuttyShrimp** [Pure-L0G1C/Instagram#73]
After a while the browsers stop to renew it always start at around 1900 Attempts I have tried on multiple devices but it's always the same problem

**Comment by Pure-L0G1C** [comment]
Do the attempts also stop renewing? Because sometimes a new browser is created as soon as another one is destroyed.

**Comment by Pure-L0G1C** [comment]
Are you using the exe file?

**Comment by NuttyShrimp** [comment]
I’musing the python file and the attempts indeed also stop renewing

**Comment by Pure-L0G1C** [comment]
Try the exe file. I myself still don’t know what the issue is being caused by.

**Comment by NuttyShrimp** [comment]
Now it worked with the exe file
