### ISSUE TITLE
Fails to search for proxies after some time

### ISSUE THREAD

**Issue by hhjkkh10** [Pure-L0G1C/Instagram#75]
The script works how it is meant to and attempts to log in. But after a while it can no longer find any proxies. And when i search up the proxy list link online it doesn't load. What could be the issue?

**Comment by Pure-L0G1C** [comment]
I don’t know, it doesn’t sound like it’s an issue with the program. You can try restarting the program or your computer, maybe that will help

**Comment by m-henderson** [comment]
@hhjkkh10 do you have any further input? if not, we need to close this issue.

**Comment by Pure-L0G1C** [comment]
Nah, I think you can close it Michael

**Comment by Pure-L0G1C** [comment]
@m-henderson
