### ISSUE TITLE
Fail at first attempt

### ISSUE THREAD

**Issue by CancerKidMaxxx** [Pure-L0G1C/Instagram#76]
Hey, i've been trying to start an attack but as soon as it's done the first attempt this shows:

![image](https://user-images.githubusercontent.com/42348705/52570471-c243f280-2e13-11e9-9ca6-b937e885a612.png)

Thanks for the help!

**Comment by Pure-L0G1C** [comment]
It says passwords not found. It seems like you only have one password in your password list

**Comment by CancerKidMaxxx** [comment]
Can you send me a file in which are passwords? I dont know what to put there

**Comment by callmelucifer** [comment]
Edit wordlist.lst

**Comment by CancerKidMaxxx** [comment]
And how do i crack a strangers account without knowing a word?

**Comment by Pure-L0G1C** [comment]
That sounds illegal.

**Comment by CancerKidMaxxx** [comment]
Its for an educational purpose

**Comment by Pure-L0G1C** [comment]
Bruh?

**Comment by Pure-L0G1C** [comment]
You use a password generator, or use a word-list from online
