### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by SimplePotato** [Pure-L0G1C/Instagram#80]
When I use English based wordlists all works ok. But recently I try to use some [Italian wordlists](https://github.com/napolux/paroleitaliane/tree/master/paroleitaliane) and some of them are throwing me Unicode Error as it showed in a screenshot...
![Screenshot (53)](https://user-images.githubusercontent.com/34000272/54482369-bc8e6200-4842-11e9-96c0-d21b7a5e4367.png)

**Comment by Pure-L0G1C** [comment]
Alright I’ll take a look at it. Thanks for letting me know

**Comment by Pure-L0G1C** [comment]
Can you tell me the exact wordlist you were using? I can't get it to crash.

**Comment by SimplePotato** [comment]
Lista_Badwords.txt is one of them.

**Comment by Pure-L0G1C** [comment]
I still can't get it to crash. Are you using the latest version of the program?

**Comment by SimplePotato** [comment]
Ok, then the issue is on my side... Yes, I'm on the latest version(2.1.0). I'm also using the script on raspberryPi3 but I think this shouldn't be an issue. Tomorrow when I get home, I'll try to run it on my laptop.
I'll try to investigate it a bit more and when I find the solution I'll let you know.

**Comment by SimplePotato** [comment]
I didn't solve the problem yet, but it's certainly raspberrian fault. Tried the script on 2 laptops and it's working great. 
I'm closing this issue since the problem could take a long time to be solved :)
